### ISSUE TITLE
Does 0.22 work with lastest jenkins? 

### ISSUE THREAD

**Issue by svr678** [justnom/proxmox-plugin#4]
Hi,

Before the jenkins 2.49 , it almost works for us(have to add 2 servers and switch to another one to have the datacenter infomations), but after 2.49 jenkins, it can not work anymore, could you please find out the root cause? Thanks a lot!

displays "http 404" when creating new node, seems it cant get datacenter infomation and will not to try it again...

Best regards

**Comment by justnom** [comment]
Sorry, but I'm not supporting this anymore for Jenkins > 2.49.
